apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: parent-template
  title: Parent Template with Conditional Steps
  description: A template that includes different steps based on user selection.
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Component Information
      required: ["componentName"]
      properties:
        componentName:
          type: string
          description: Name of the new component.
          
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Project Type
      required: ["projectType"]
      properties:
        projectType:
          type: string
          enum: ["frontend", "backend"]
          description: Select the type of project.

  steps:
    # Step 1: Dynamically Select the Child Template
  - id: fetch-child-template
    name: Load Child Template
    action: fetch:template
    input:
      url: >-
        {% if parameters.projectType == "frontend" %}
           ./templates/frontend-template.yaml
        {% else %}
          ./templates/backend-template.yaml
        {% endif %}
      values:
        componentName: ${{ parameters.componentName }}


