apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  ${{ values.name | dump }}
  description: ${{ values.description }}
  tags:
    - github
    - aks
    - nodejs
  links:
    - url: https://github.com/${{values.owner}}/${{values.name}}
      title: ${{values.name}} Repository
  annotations:
    github.com/project-slug: ${{ values.owner + "/" + values.name }}
    github.com/workflow-ref: .github/workflows/deploy.yaml@main
    backstage.io/managed-by-location: url:https://github.com/${{values.owner}}/${{values.name}}
    backstage.io/managed-by-origin-location: url:https://github.com/${{values.owner}}/${{values.name}}
    backstage.io/kubernetes-id: ${{ values.name | dump }}
    backstage.io/kubernetes-cluster: ${{ values.cluster | dump }}
    backstage.io/kubernetes-namespace: '${{values.namespace}}'
    # backstage.io/techdocs-ref: dir:.
    #backstage.io/techdocs-ref: url:http://<your-service-endpoint>
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: production
